[package]
name = "itaots-reddit"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
dotenv = "0.15.0"
itertools = "0.10.5"
reqwest = "0.11.16"
roux = "2.2.6"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = { version = "1", features = ["full"] }
